config/routes.rb
Hwfinal::Application.routes.draw do
  resources :ratings

  resources :members do
	  resources :ratings
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :ratings
	validates :name, :presence => true
	validates :body, :presence => true
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :member
	validates :member_id, :presence => true
	validates :met_your_expectations, :presence => true
	validates :quality_of_meals_and_snacks, :presence => true
	validates :seminar_room_and_facilities, :presence => true
	validates :presentation_style, :presence => true
	validates :pace_of_instruction_was_appropriate_for_learning_goals, :presence => true
	validates :able_to_effectively_answer_questions, :presence => true
	validates :clearly_written_and_mistake_free, :presence => true
	validates :sufficient_detail_for_the_topics_covered, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
before_filter :authenticate, :except => [:index, :show]
  # GET /members
  # GET /members.xml
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'Member was successfully created.') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
private
def authenticate
	authenticate_or_request_with_http_basic do |name, password|
		name == "admin" && password == "letmein"
	end
end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    	  @member = Member.find(params[:member_id])
	  @rating = @member.ratings.create!(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@rating, :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to(@rating, :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hwfinal</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.body %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Body:</b>
  <%= @member.body %>
</p>
<h2>Evaluation Form</h2>

<% form_for [@member, Rating.new] do |f| %>
	<table>
	<tr>
		<th>Seminar</th><th>Evaluation (5-1) 5=Excellent, 1=Poor</th><th>Comments</th>
	</tr>
	<tr>
		<td>Met your expectations</td><td><%= f.radio_button :met_your_expectations, '5' %>5<%= f.radio_button :met_your_expectations, '4' %>4<%= f.radio_button :met_your_expectations, '3' %>3<%= f.radio_button :met_your_expectations, '2' %>2<%= f.radio_button :met_your_expectations, '1' %>1</td><td><%= f.text_area :comment1 %></td>
	</tr>
	<tr>
		<td>Quality of meals and snacks</td><td><%= f.radio_button :quality_of_meals_and_snacks, '5' %>5<%= f.radio_button :quality_of_meals_and_snacks, '4' %>4<%= f.radio_button :quality_of_meals_and_snacks, '3' %>3<%= f.radio_button :quality_of_meals_and_snacks, '2' %>2<%= f.radio_button :quality_of_meals_and_snacks, '1' %>1</td><td><%= f.text_area :comment2 %></td>
	</tr>
	<tr>
		<td>Seminar room and facilities</td><td><%= f.radio_button :seminar_room_and_facilities, '5' %>5<%= f.radio_button :seminar_room_and_facilities, '4' %>4<%= f.radio_button :seminar_room_and_facilities, '3' %>3<%= f.radio_button :seminar_room_and_facilities, '2' %>2<%= f.radio_button :seminar_room_and_facilities, '1' %>1</td><td><%= f.text_area :comment3 %></td>
	</tr>
	<tr>
		<th>Instructor</th><th>Evaluation (5-1) 5=Excellent, 1=Poor</th><th>Comments</th>
	</tr>
	<tr>
		<td>Presentation style</td><td><%= f.radio_button :presentation_style, '5' %>5<%= f.radio_button :presentation_style, '4' %>4<%= f.radio_button :presentation_style, '3' %>3<%= f.radio_button :presentation_style, '2' %>2<%= f.radio_button :presentation_style, '1' %>1</td><td><%= f.text_area :comment4 %></td>
	</tr>
	<tr>
		<td>Pace of instruction was appropriate for learning goals</td><td><%= f.radio_button :pace_of_instruction_was_appropriate_for_learning_goals, '5' %>5<%= f.radio_button :pace_of_instruction_was_appropriate_for_learning_goals, '4' %>4<%= f.radio_button :pace_of_instruction_was_appropriate_for_learning_goals, '3' %>3<%= f.radio_button :pace_of_instruction_was_appropriate_for_learning_goals, '2' %>2<%= f.radio_button :pace_of_instruction_was_appropriate_for_learning_goals, '1' %>1</td><td><%= f.text_area :comment5 %></td>
	</tr>
	<tr>
		<td>Able to effectively answer questions</td><td><%= f.radio_button :able_to_effectively_answer_questions, '5' %>5<%= f.radio_button :able_to_effectively_answer_questions, '4' %>4<%= f.radio_button :able_to_effectively_answer_questions, '3' %>3<%= f.radio_button :able_to_effectively_answer_questions, '2' %>2<%= f.radio_button :able_to_effectively_answer_questions, '1' %>1</td><td><%= f.text_area :comment6 %></td>
	</tr>
	<tr>
		<th>Materials</th><th>Evaluation (5-1) 5=Excellent, 1=Poor</th><th>Comments</th>
	</tr>
	<tr>
		<td>Clearly written and mistake free</td><td><%= f.radio_button :clearly_written_and_mistake_free, '5' %>5<%= f.radio_button :clearly_written_and_mistake_free, '4' %>4<%= f.radio_button :clearly_written_and_mistake_free, '3' %>3<%= f.radio_button :clearly_written_and_mistake_free, '2' %>2<%= f.radio_button :clearly_written_and_mistake_free, '1' %>1</td><td><%= f.text_area :comment7 %></td>
	</tr>
	<tr>
		<td>Sufficient detail for the topics covered</td><td><%= f.radio_button :sufficient_detail_for_the_topics_covered, '5' %>5<%= f.radio_button :sufficient_detail_for_the_topics_covered, '4' %>4<%= f.radio_button :sufficient_detail_for_the_topics_covered, '3' %>3<%= f.radio_button :sufficient_detail_for_the_topics_covered, '2' %>2<%= f.radio_button :sufficient_detail_for_the_topics_covered, '1' %>1</td><td><%f.text_area :comment8 %></td>
	</tr>
</table>
<p>
<b>Additional Comments</b><br />
<%= f.text_area :additional_comments %>
</p>
<p><%= f.submit "Submit" %></p>
<% end %>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :met_your_expectations %><br />
    <%= f.text_field :met_your_expectations %>
  </div>
  <div class="field">
    <%= f.label :comment1 %><br />
    <%= f.text_area :comment1 %>
  </div>
  <div class="field">
    <%= f.label :quality_of_meals_and_snacks %><br />
    <%= f.text_field :quality_of_meals_and_snacks %>
  </div>
  <div class="field">
    <%= f.label :comment2 %><br />
    <%= f.text_area :comment2 %>
  </div>
  <div class="field">
    <%= f.label :seminar_room_and_facilities %><br />
    <%= f.text_field :seminar_room_and_facilities %>
  </div>
  <div class="field">
    <%= f.label :comment3 %><br />
    <%= f.text_area :comment3 %>
  </div>
  <div class="field">
    <%= f.label :presentation_style %><br />
    <%= f.text_field :presentation_style %>
  </div>
  <div class="field">
    <%= f.label :comment4 %><br />
    <%= f.text_area :comment4 %>
  </div>
  <div class="field">
    <%= f.label :pace_of_instruction_was_appropriate_for_learning_goals %><br />
    <%= f.text_field :pace_of_instruction_was_appropriate_for_learning_goals %>
  </div>
  <div class="field">
    <%= f.label :comment5 %><br />
    <%= f.text_area :comment5 %>
  </div>
  <div class="field">
    <%= f.label :able_to_effectively_answer_questions %><br />
    <%= f.text_field :able_to_effectively_answer_questions %>
  </div>
  <div class="field">
    <%= f.label :comment6 %><br />
    <%= f.text_area :comment6 %>
  </div>
  <div class="field">
    <%= f.label :clearly_written_and_mistake_free %><br />
    <%= f.text_field :clearly_written_and_mistake_free %>
  </div>
  <div class="field">
    <%= f.label :comment7 %><br />
    <%= f.text_area :comment7 %>
  </div>
  <div class="field">
    <%= f.label :sufficient_detail_for_the_topics_covered %><br />
    <%= f.text_field :sufficient_detail_for_the_topics_covered %>
  </div>
  <div class="field">
    <%= f.label :comment8 %><br />
    <%= f.text_area :comment8 %>
  </div>
  <div class="field">
    <%= f.label :additional_comments %><br />
    <%= f.text_area :additional_comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Met your expectations</th>
    <th>Comment1</th>
    <th>Quality of meals and snacks</th>
    <th>Comment2</th>
    <th>Seminar room and facilities</th>
    <th>Comment3</th>
    <th>Presentation style</th>
    <th>Comment4</th>
    <th>Pace of instruction was appropriate for learning goals</th>
    <th>Comment5</th>
    <th>Able to effectively answer questions</th>
    <th>Comment6</th>
    <th>Clearly written and mistake free</th>
    <th>Comment7</th>
    <th>Sufficient detail for the topics covered</th>
    <th>Comment8</th>
    <th>Additional comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.member_id %></td>
    <td><%= rating.met_your_expectations %></td>
    <td><%= rating.comment1 %></td>
    <td><%= rating.quality_of_meals_and_snacks %></td>
    <td><%= rating.comment2 %></td>
    <td><%= rating.seminar_room_and_facilities %></td>
    <td><%= rating.comment3 %></td>
    <td><%= rating.presentation_style %></td>
    <td><%= rating.comment4 %></td>
    <td><%= rating.pace_of_instruction_was_appropriate_for_learning_goals %></td>
    <td><%= rating.comment5 %></td>
    <td><%= rating.able_to_effectively_answer_questions %></td>
    <td><%= rating.comment6 %></td>
    <td><%= rating.clearly_written_and_mistake_free %></td>
    <td><%= rating.comment7 %></td>
    <td><%= rating.sufficient_detail_for_the_topics_covered %></td>
    <td><%= rating.comment8 %></td>
    <td><%= rating.additional_comments %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @rating.member_id %>
</p>

<p>
  <b>Met your expectations:</b>
  <%= @rating.met_your_expectations %>
</p>

<p>
  <b>Comment1:</b>
  <%= @rating.comment1 %>
</p>

<p>
  <b>Quality of meals and snacks:</b>
  <%= @rating.quality_of_meals_and_snacks %>
</p>

<p>
  <b>Comment2:</b>
  <%= @rating.comment2 %>
</p>

<p>
  <b>Seminar room and facilities:</b>
  <%= @rating.seminar_room_and_facilities %>
</p>

<p>
  <b>Comment3:</b>
  <%= @rating.comment3 %>
</p>

<p>
  <b>Presentation style:</b>
  <%= @rating.presentation_style %>
</p>

<p>
  <b>Comment4:</b>
  <%= @rating.comment4 %>
</p>

<p>
  <b>Pace of instruction was appropriate for learning goals:</b>
  <%= @rating.pace_of_instruction_was_appropriate_for_learning_goals %>
</p>

<p>
  <b>Comment5:</b>
  <%= @rating.comment5 %>
</p>

<p>
  <b>Able to effectively answer questions:</b>
  <%= @rating.able_to_effectively_answer_questions %>
</p>

<p>
  <b>Comment6:</b>
  <%= @rating.comment6 %>
</p>

<p>
  <b>Clearly written and mistake free:</b>
  <%= @rating.clearly_written_and_mistake_free %>
</p>

<p>
  <b>Comment7:</b>
  <%= @rating.comment7 %>
</p>

<p>
  <b>Sufficient detail for the topics covered:</b>
  <%= @rating.sufficient_detail_for_the_topics_covered %>
</p>

<p>
  <b>Comment8:</b>
  <%= @rating.comment8 %>
</p>

<p>
  <b>Additional comments:</b>
  <%= @rating.additional_comments %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>